### Here i build a baseline model per dataset

In [1]:
import os
import pandas as pd
%matplotlib inline
import matplotlib.pyplot as plt
from sklearn.ensemble import GradientBoostingRegressor
from sklearn import metrics
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import r2_score
from sklearn import preprocessing
from sklearn.model_selection import RandomizedSearchCV

In [22]:
os.getcwd()
os.chdir("C:\\Users\\Jacco Bruin .LAPTOP-ACFSBHIL\\THESIS")
df1 = pd.read_csv('1_year_dataset(3)(without_outliers).csv') 
#df2 = pd.read_csv('6_year_dataset(2)(with_cat).csv') 

df12 = df1["Ticker_x"]

df1 = df1.set_index("Ticker_x")

df1.head()

,year,EBITDA,Total Debt,Free Cash Flow,Gross Profit Margin,Operating Margin,Net Profit Margin,Return on Equity,Return on Assets,Free Cash Flow to Net Income,...,Net portfolio equity inflows,Economic growth forecast,Inflation forecast,Unemployment rate forecast,Political stability index (-2.5 weak; 2.5 strong),Interest rates on bank credit to the private sector,Open,close,1_year,1_year_cat
Ticker_x,,,,,,,,,,,,,,,,,,,,,
AAL,2010,1.275000e+09,9.125501e+09,-188401000.0,0.2303,0.0139,-0.0212,0.1194,-0.0188,0.8026,...,178952.99,2.71,1.69,9.61,0.44,3.25,9.29,5.44,-0.4101,0
AAL,2011,4.900000e+07,8.220000e+09,-188401000.0,0.1824,-0.0401,-0.0825,0.2783,-0.0830,0.5392,...,123357.00,1.55,3.09,8.93,0.59,3.25,5.44,10.35,0.8044,1
AAL,2012,1.163000e+09,8.535000e+09,-188401000.0,0.2056,0.0060,-0.0755,0.2349,-0.0798,0.5538,...,239066.01,2.28,1.82,8.08,0.63,3.25,10.35,18.98,0.8044,1
AAL,2013,2.419000e+09,9.125501e+09,-188401000.0,0.2594,0.0523,-0.0686,0.4827,-0.0434,0.7072,...,-62642.00,1.84,1.32,7.36,0.64,3.25,18.98,34.72,0.8044,1
AAL,2014,2.450000e+09,9.125501e+09,-188401000.0,0.2815,0.0996,0.0676,0.4827,0.0667,-0.1960,...,154312.00,2.29,0.52,6.16,0.58,3.25,34.72,38.50,0.1089,1

In [23]:
#scale data and add columns and index to it 

df11 = df1.columns
x = df1.values 
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
df1 = pd.DataFrame(x_scaled)
df1.columns = [df11]
df1.index = [df12]

In [27]:
X = df1.iloc[:,1:19]   
y = df1.iloc[:,-2]
X.columns

MultiIndex([(                      'EBITDA',),
            (                  'Total Debt',),
            (              'Free Cash Flow',),
            (         'Gross Profit Margin',),
            (            'Operating Margin',),
            (           'Net Profit Margin',),
            (            'Return on Equity',),
            (            'Return on Assets',),
            ('Free Cash Flow to Net Income',),
            (               'Current Ratio',),
            ( 'Liabilities to Equity Ratio',),
            (                  'Debt Ratio',),
            (   'Earnings Per Share, Basic',),
            ( 'Earnings Per Share, Diluted',),
            (             'Sales Per Share',),
            (            'Equity Per Share',),
            (    'Free Cash Flow Per Share',),
            (           'Pietroski F-Score',)],
           )

In [28]:
# select the mean of the target values and make this equal to rows of dataset

x = df1.shape[0]
y_pred = [y.mean()] * x

In [29]:
# evalute the score

from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error

MSE = mean_squared_error(y,y_pred)
MAE = mean_absolute_error(y,y_pred)
R2 =  r2_score(y,y_pred)  

n = len(y)
p = X.shape[1]

Adj_R2 = 1-(1-R2)*(n-1)/(n-p-1)


print(MSE)
print(MAE)
print("R2_adj of test Model with Cross Validation is:", Adj_R2)

0.06715004589991908
0.20688874862878073
R2_adj of test Model with Cross Validation is: -0.004399902224395014