### Build dataset for 6 year predictions

In [1]:
import numpy as np
import pandas as pd
import os
import missingno as msno

In [2]:
os.getcwd()
os.chdir("C:\\Users\\Jacco Bruin .LAPTOP-ACFSBHIL\\THESIS")

In [3]:
df1 = pd.read_csv("dataset_edition(4)(test_version)(nomissingvalues).csv")
df1.shape

(4521, 33)

In [4]:
df1 = df1.iloc[: , 1:]  # run this to delete the irrelevant index columns

In [5]:
df1

,Ticker_x,year,EBITDA,Total Debt,Free Cash Flow,Gross Profit Margin,Operating Margin,Net Profit Margin,Return on Equity,Return on Assets,...,Inflation: percent change in the Consumer Price Index,Unemployment rate,Net portfolio equity inflows,Economic growth forecast,Inflation forecast,Unemployment rate forecast,Political stability index (-2.5 weak; 2.5 strong),Interest rates on bank credit to the private sector,Open,profit/loss
0,AAL,2010,1.275000e+09,1.113600e+10,-3.780000e+08,0.23031,0.01389,-0.02124,0.11939,-0.01877,...,1.6,9.63,178952.99,2.71,1.69,9.61,0.44,3.25,9.29,0.0000
1,AAL,2011,4.900000e+07,8.220000e+09,-1.067000e+09,0.18237,-0.04325,-0.08253,0.27830,-0.08298,...,3.2,8.95,123357.00,1.55,3.09,8.93,0.59,3.25,5.44,-0.4144
2,AAL,2012,1.163000e+09,8.535000e+09,-1.039000e+09,0.20563,0.00595,-0.07548,0.23488,-0.07980,...,2.1,8.07,239066.01,2.28,1.82,8.08,0.63,3.25,10.35,0.1141
3,AAL,2013,2.419000e+09,1.679900e+10,-1.297000e+09,0.25943,0.05231,-0.06858,0.67155,-0.04338,...,1.5,7.38,-62642.00,1.84,1.32,7.36,0.64,3.25,18.98,1.0431
4,AAL,2014,5.762000e+09,1.772000e+10,-5.650000e+08,0.28150,0.09962,0.06757,1.42603,0.06667,...,1.6,6.17,154312.00,2.29,0.52,6.16,0.58,3.25,34.72,2.7374
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4516,ZEUS,2016,6.164000e+07,1.664240e+08,3.010700e+07,0.14743,0.04003,-0.00102,-0.00425,-0.00194,...,1.3,4.87,-139700.99,1.67,2.18,4.88,0.40,3.51,22.20,-0.0484
4517,ZEUS,2017,8.436200e+07,1.971650e+08,2.680700e+07,0.14132,0.04943,0.01425,0.06957,0.03139,...,2.1,4.36,149634.01,2.26,2.17,4.35,0.29,4.10,21.99,-0.0574
4518,ZEUS,2018,7.508700e+07,3.025300e+08,-4.061800e+07,0.14260,0.03326,0.01968,0.10997,0.04438,...,2.4,3.90,156916.01,2.92,1.91,3.89,0.42,4.90,20.96,-0.1016
4519,ZEUS,2019,3.615800e+07,1.929250e+08,1.306630e+08,0.12633,0.01052,0.00244,0.01251,0.00594,...,1.8,3.67,-244072.01,2.29,2.06,3.68,0.13,5.28,14.49,-0.3789
4520,ZEUS,2020,2.058100e+07,1.606090e+08,5.339400e+07,0.13933,0.00046,-0.00453,-0.01859,-0.00873,...,1.2,8.31,725723.97,-3.41,1.55,8.11,-0.02,3.54,11.01,-0.5281

In [6]:
# select the years 2010 till 2014 (more not possible because 2014 + 6 = 2020)


df1_uni = np.unique(df1["Ticker_x"])

data = pd.DataFrame()

for i in df1_uni:
    x = df1[df1["Ticker_x"] == i]
    
    for j in x["year"]:
        y = x[x["year"] == j]
        if j <= 2014:
            data = pd.concat([data, y])
    
data = data.reset_index()
data.iloc[1:20,:]

,index,Ticker_x,year,EBITDA,Total Debt,Free Cash Flow,Gross Profit Margin,Operating Margin,Net Profit Margin,Return on Equity,...,Inflation: percent change in the Consumer Price Index,Unemployment rate,Net portfolio equity inflows,Economic growth forecast,Inflation forecast,Unemployment rate forecast,Political stability index (-2.5 weak; 2.5 strong),Interest rates on bank credit to the private sector,Open,profit/loss
1,1,AAL,2011,4.900000e+07,8.220000e+09,-1.067000e+09,0.18237,-0.04325,-0.08253,0.27830,...,3.2,8.95,123357.00,1.55,3.09,8.93,0.59,3.25,5.44,-0.4144
2,2,AAL,2012,1.163000e+09,8.535000e+09,-1.039000e+09,0.20563,0.00595,-0.07548,0.23488,...,2.1,8.07,239066.01,2.28,1.82,8.08,0.63,3.25,10.35,0.1141
3,3,AAL,2013,2.419000e+09,1.679900e+10,-1.297000e+09,0.25943,0.05231,-0.06858,0.67155,...,1.5,7.38,-62642.00,1.84,1.32,7.36,0.64,3.25,18.98,1.0431
4,4,AAL,2014,5.762000e+09,1.772000e+10,-5.650000e+08,0.28150,0.09962,0.06757,1.42603,...,1.6,6.17,154312.00,2.29,0.52,6.16,0.58,3.25,34.72,2.7374
5,11,AAP,2010,7.493700e+08,3.018240e+08,8.534970e+08,0.49978,0.09872,0.05840,0.33294,...,1.6,9.63,178952.99,2.71,1.69,9.61,0.44,3.25,59.22,0.0000
6,12,AAP,2011,8.405910e+08,4.159840e+08,1.001269e+09,0.49742,0.10771,0.06396,0.46547,...,3.2,8.95,123357.00,1.55,3.09,8.93,0.59,3.25,57.84,-0.0233
7,13,AAP,2012,8.468590e+08,6.050880e+08,9.034100e+08,0.49928,0.10593,0.06248,0.32020,...,2.1,8.07,239066.01,2.28,1.82,8.08,0.63,3.25,68.53,0.1572
8,14,AAP,2013,8.681130e+08,1.053584e+09,8.555260e+08,0.50081,0.10168,0.06033,0.25838,...,1.5,7.38,-62642.00,1.84,1.32,7.36,0.64,3.25,82.70,0.3965
9,15,AAP,2014,1.136403e+09,1.636893e+09,1.051393e+09,0.45243,0.08652,0.05017,0.24655,...,1.6,6.17,154312.00,2.29,0.52,6.16,0.58,3.25,129.89,1.1933
10,22,AAWW,2010,4.967670e+08,4.872330e+08,5.869110e+08,0.46745,0.33968,0.10600,0.13505,...,1.6,9.63,178952.99,2.71,1.69,9.61,0.44,3.25,50.73,0.0000
11,23,AAWW,2011,4.490980e+08,7.500160e+08,3.805250e+08,0.41485,0.28736,0.06872,0.08418,...,3.2,8.95,123357.00,1.55,3.09,8.93,0.59,3.25,33.01,-0.3493
12,24,AAWW,2012,5.928200e+08,1.304042e+09,6.067040e+08,0.45592,0.31629,0.07893,0.10087,...,2.1,8.07,239066.01,2.28,1.82,8.08,0.63,3.25,52.17,0.0284
13,25,AAWW,2013,6.311050e+08,1.696625e+09,6.764940e+08,0.47344,0.31953,0.05663,0.07097,...,1.5,7.38,-62642.00,1.84,1.32,7.36,0.64,3.25,46.24,-0.0885
14,26,AAWW,2014,7.024370e+08,1.917940e+09,6.771530e+08,0.48923,0.31354,0.05934,0.07530,...,1.6,6.17,154312.00,2.29,0.52,6.16,0.58,3.25,33.04,-0.3487
15,33,ABG,2010,1.430000e+08,5.438000e+08,2.970000e+07,0.16669,0.03257,0.01013,0.13271,...,1.6,9.63,178952.99,2.71,1.69,9.61,0.44,3.25,14.23,0.0000
16,34,ABG,2011,1.537000e+08,4.586000e+08,-6.120000e+07,0.16910,0.03168,0.01640,0.20790,...,3.2,8.95,123357.00,1.55,3.09,8.93,0.59,3.25,16.40,0.1525
17,35,ABG,2012,2.085000e+08,4.660000e+08,1.370000e+07,0.16455,0.04005,0.01771,0.20407,...,2.1,8.07,239066.01,2.28,1.82,8.08,0.63,3.25,28.15,0.9782
18,36,ABG,2013,2.504000e+08,5.544000e+08,9.540000e+07,0.16420,0.04238,0.02045,0.22238,...,1.5,7.38,-62642.00,1.84,1.32,7.36,0.64,3.25,53.37,2.7505
19,37,ABG,2014,2.946000e+08,6.974000e+08,1.743000e+08,0.16483,0.04571,0.01902,0.25084,...,1.6,6.17,154312.00,2.29,0.52,6.16,0.58,3.25,63.84,3.4863

In [10]:
#select target values 2016 till 2020

df1_uni = np.unique(df1["Ticker_x"])

data2 = pd.DataFrame()

for i in df1_uni:
    x = df1[df1["Ticker_x"] == i]
    for j in x["year"]:
        y = x[x["year"] == j]
        if j >= 2016:
            data2 = pd.concat([data2, y])

data2.head()

,Ticker_x,year,EBITDA,Total Debt,Free Cash Flow,Gross Profit Margin,Operating Margin,Net Profit Margin,Return on Equity,Return on Assets,...,Inflation: percent change in the Consumer Price Index,Unemployment rate,Net portfolio equity inflows,Economic growth forecast,Inflation forecast,Unemployment rate forecast,Political stability index (-2.5 weak; 2.5 strong),Interest rates on bank credit to the private sector,Open,profit/loss
6,AAL,2016,7.102000e+09,2.434400e+10,3.371000e+09,0.33265,0.13151,0.06660,0.70700,0.05219,...,1.3,4.87,-139700.99,1.67,2.18,4.88,0.40,3.51,36.46,2.9247
7,AAL,2017,6.248000e+09,2.506500e+10,2.616000e+09,0.30576,0.09927,0.03008,-1.64359,0.02429,...,2.1,4.36,149634.01,2.26,2.17,4.35,0.29,4.10,47.52,4.1152
8,AAL,2018,4.815000e+09,2.447300e+10,2.183000e+09,0.54200,0.05963,0.03170,-8.35503,0.02331,...,2.4,3.90,156916.01,2.92,1.91,3.89,0.42,4.90,41.41,3.4575
9,AAL,2019,5.383000e+09,2.431500e+10,1.972000e+09,0.54580,0.06697,0.03684,-14.28814,0.02810,...,1.8,3.67,-244072.01,2.29,2.06,3.68,0.13,5.28,27.08,1.9150
10,AAL,2020,-8.051000e+09,3.259300e+10,-1.025400e+10,0.31170,-0.60108,-0.51249,1.29387,-0.14329,...,1.2,8.31,725723.97,-3.41,1.55,8.11,-0.02,3.54,12.86,0.3843

In [11]:
#sort the dataset on alphabet and year

data2 = data2.sort_values(by=['Ticker_x', "year"])
data = data.sort_values(by=['Ticker_x',"year"])

In [18]:
#select only the open column, which will be the closing price in our new dataset

closed = data2["Open"]
closed = closed.reset_index()
closed = closed.iloc[0:,1:2]
closed.iloc[1:20,:]

      Open
1    47.52
2    41.41
3    27.08
4    12.86
5   148.53
6    99.58
7   169.02
8   165.59
9   155.78
10   42.44
11   65.85
12   63.99
13   25.40
14   56.55
15   55.37
16   61.15
17   69.15
18  102.70
19  105.37

In [19]:
data["close"] = closed  # add the close price to the dataset

In [20]:
data["6_years"] = round((data["close"] - data["Open"]) / data["Open"],4)  # calculate the difference between open and close stock price

In [21]:
data = data.drop(columns = "profit/loss")  # drop the profit/loss since we have made a new proft/loss

In [28]:
data = round(data,4)  # round the data

In [34]:
data.to_csv("6_year_dataset(1).csv")

### We now have the 6 years dataset. In the file "recode_outliers", we will take care of the outliers