In [1]:
import os
import pandas as pd
import numpy as np
%matplotlib inline
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import r2_score
from sklearn.model_selection import cross_validate
from sklearn import preprocessing
from sklearn.model_selection import RandomizedSearchCV

In [2]:
os.getcwd()
os.chdir("C:\\Users\\Jacco Bruin .LAPTOP-ACFSBHIL\\THESIS")
df1 = pd.read_csv('6_year_dataset(4)(without_outliers).csv')  # change dataset to check result 3 year dataset and 1 year dataset 

df12 = df1["Ticker_x"]

df1 = df1.set_index("Ticker_x")

df1.head()

,year,EBITDA,Total Debt,Free Cash Flow,Gross Profit Margin,Operating Margin,Net Profit Margin,Return on Equity,Return on Assets,Free Cash Flow to Net Income,...,Net portfolio equity inflows,Economic growth forecast,Inflation forecast,Unemployment rate forecast,Political stability index (-2.5 weak; 2.5 strong),Interest rates on bank credit to the private sector,Open,close,6_years,6_year_cat
Ticker_x,,,,,,,,,,,,,,,,,,,,,
AAL,2010,1.275000e+09,6.870000e+09,-191378000.0,0.2303,0.0139,-0.0212,0.1194,-0.0188,0.8026,...,178952.99,2.71,1.69,9.61,0.44,3.25,9.29,36.46,2.9247,2
AAL,2011,4.900000e+07,6.870000e+09,-191378000.0,0.1824,-0.0298,-0.0825,0.2783,-0.0830,0.5392,...,123357.00,1.55,3.09,8.93,0.59,3.25,5.44,47.52,4.3735,2
AAL,2012,1.163000e+09,6.870000e+09,-191378000.0,0.2056,0.0060,-0.0755,0.2349,-0.0798,0.5538,...,239066.01,2.28,1.82,8.08,0.63,3.25,10.35,41.41,3.0010,2
AAL,2013,1.986506e+09,6.870000e+09,-191378000.0,0.2594,0.0523,-0.0686,0.4780,-0.0434,0.7072,...,-62642.00,1.84,1.32,7.36,0.64,3.25,18.98,27.08,0.4268,1
AAL,2014,1.986506e+09,6.870000e+09,-191378000.0,0.2815,0.0996,0.0676,0.4780,0.0667,-0.1960,...,154312.00,2.29,0.52,6.16,0.58,3.25,34.72,12.86,-0.6296,0

In [3]:
#scale data and add columns and index to it 

df11 = df1.columns
x = df1.values 
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
df1 = pd.DataFrame(x_scaled)
df1.columns = [df11]
df1.index = [df12]

In [42]:
selection_6_years = [1,2,3,4,5,7,8,9,10,11,12,15,16,17,20] #index number are here one less than in file "feature_selection" because different indicies     
selection_3_years = [4,10,13,14,16,17]                           
selection_1_year = [1,2,3,4,5,6,7,8,9,10,11,12,15,16,17,24,27]

X = df1.iloc[:, selection_6_years]
y = df1.iloc[:, -2]
X.columns

MultiIndex([(                             'EBITDA',),
            (                         'Total Debt',),
            (                     'Free Cash Flow',),
            (                'Gross Profit Margin',),
            (                   'Operating Margin',),
            (                   'Return on Equity',),
            (                   'Return on Assets',),
            (       'Free Cash Flow to Net Income',),
            (                      'Current Ratio',),
            (        'Liabilities to Equity Ratio',),
            (                         'Debt Ratio',),
            (                    'Sales Per Share',),
            (                   'Equity Per Share',),
            (           'Free Cash Flow Per Share',),
            ('GDP per capita current U.S. dollars',)],
           )

### Code to find the best hyperparameters

In [8]:
# randomsearchCV to optimalize the hyperparameters

gradient = GradientBoostingRegressor()
LR = {'max_depth': np.arange(1,11,2),         
      'n_estimators': np.arange(50,500,50),  
      #'max_leaf_nodes': np.arange(0,2,1),     
      'max_features': np.arange(5,20,3),        
      'learning_rate': np.arange(0.02,0.2,0.02)} 

clf = RandomizedSearchCV(gradient, LR, n_iter=60, cv = 10, scoring = "neg_mean_absolute_error", n_jobs = -1, random_state = 999 )
search = clf.fit(X, y)
search.best_params_, search.best_score_

C:\Users\Jacco Bruin .LAPTOP-ACFSBHIL\anaconda3\envs\tens\lib\site-packages\sklearn\model_selection\_search.py:925: UserWarning: One or more of the test scores are non-finite: [        nan -0.21009529         nan -0.2082283          nan         nan
 -0.2043789  -0.20869563 -0.21086587 -0.20976426 -0.20903448         nan
 -0.21269177         nan -0.20874912 -0.20453533 -0.21689149 -0.21423026
 -0.2091419  -0.20392607         nan -0.20442272         nan -0.21024282
 -0.20610334 -0.20446333 -0.20312174 -0.20937426 -0.2087767  -0.20502714
 -0.20444735 -0.21218988         nan -0.21005135         nan         nan
 -0.21682884 -0.21291334 -0.20952715 -0.21554593         nan -0.20513025
 -0.21699071         nan -0.20470256 -0.21487566 -0.21393782 -0.20849186
 -0.21177445 -0.2117421  -0.20821083 -0.21291006 -0.20600637 -0.20787404
         nan         nan -0.20459554         nan -0.21103522 -0.21395309]
  category=UserWarning

({'n_estimators': 50,
  'max_features': 11,
  'max_depth': 3,
  'learning_rate': 0.16},
 -0.2031217386019577)

## When the best hyperparameters were found, the following code was used to find the results.

In [7]:
selection_6_years = [1,2,3,4,5,7,8,9,10,11,12,15,16,17,20] #index number are here one less than in file "feature_selection" because different dataset     
selection_3_years = [4,10,13,14,16,17]                           
selection_1_year = [1,2,3,4,5,6,7,8,9,10,11,12,15,16,17,24,27]

X = df1.iloc[:, 1:19]   # [:,1:29] = whole dataset, [:,1:19] = finanical ratios only, [:,19:29] = macroeconomic variables only
y = df1.iloc[:, -2]
X.columns

MultiIndex([(                      'EBITDA',),
            (                  'Total Debt',),
            (              'Free Cash Flow',),
            (         'Gross Profit Margin',),
            (            'Operating Margin',),
            (           'Net Profit Margin',),
            (            'Return on Equity',),
            (            'Return on Assets',),
            ('Free Cash Flow to Net Income',),
            (               'Current Ratio',),
            ( 'Liabilities to Equity Ratio',),
            (                  'Debt Ratio',),
            (   'Earnings Per Share, Basic',),
            ( 'Earnings Per Share, Diluted',),
            (             'Sales Per Share',),
            (            'Equity Per Share',),
            (    'Free Cash Flow Per Share',),
            (           'Pietroski F-Score',)],
           )

In [8]:
# without outlier / no scaled data
gradient = GradientBoostingRegressor(n_estimators = 250, max_depth = 1, learning_rate = 0.1,max_features = 17, random_state = 999)
result_cv = cross_validate(gradient, X, y, cv = 5, scoring = ["r2", "neg_mean_squared_error", "neg_mean_absolute_error"], return_train_score=True)
#print("R2:\n", result_cv['test_r2'])
#print("MSE:\n", result_cv['test_neg_mean_squared_error'])   
#print("MAE:\n", result_cv['test_neg_mean_absolute_error'])   


print("-----------------")
#print("Accuracy of Model with Cross Validation is:",result_cv['test_r2'].mean())
print("Accuracy of Model with Cross Validation is:",result_cv['test_neg_mean_squared_error'].mean()*-1)
print("Accuracy of Model with Cross Validation is:", result_cv['test_neg_mean_absolute_error'].mean()*-1)

### formula r2_adj 

R2 = result_cv["test_r2"].mean()
n = len(y)
p = X.shape[1]

Adj_R2 = 1-(1-R2)*(n-1)/(n-p-1)

print("R2_adj of test Model with Cross Validation is:", Adj_R2)


### down the training result to check if the data was not overfitting

#print("-----------------")
#print("Accuracy of Model with Cross Validation is:",result_cv['train_r2'].mean())
#print("Accuracy of Model with Cross Validation is:",result_cv['train_neg_mean_squared_error'].mean()*-1)
#print("Accuracy of Model with Cross Validation is:", result_cv['train_neg_mean_absolute_error'].mean()*-1)

-----------------
Accuracy of Model with Cross Validation is: 0.07243392697700375
Accuracy of Model with Cross Validation is: 0.21167236022323274
R2_adj of test Model with Cross Validation is: -0.00020722069108969343